modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "kubejsprojecte"
version = "${file.jarVersion}"
displayName = "KubeJS ProjectE"
authors = "BlatFan, BobVarioa"
description = '''

'''
[[dependencies.kubejsprojecte]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsprojecte]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsprojecte]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[2001.6.4-build.114,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsprojecte]]
    modId = "projecte"
    mandatory = true
    versionRange = "[1.0.1,)"
    ordering = "NONE"
    side = "BOTH"