modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "kubejsprojecte"
version = "${file.jarVersion}"
displayName = "KubeJS ProjectE"
authors = "BobVarioa"
description = '''

'''
[[dependencies.kubejsprojecte]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsprojecte]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsprojecte]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1902.6.1-build.282,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsprojecte]]
    modId = "projecte"
    mandatory = true
    versionRange = "[1.0.1B,)"
    ordering = "NONE"
    side = "BOTH"